### PR TITLE
import raster mode geocode_slc

### PR DESCRIPTION
**Pull request by LiangJYu**
This PR addresses this [isce3 issue](https://github-fn.jpl.nasa.gov/isce-3/isce/issues/1327) so corrects the imports so the `geocode_slc` raster mode is used.

### CODE REVIEW

**Review by scottstanie — APPROVED** [review]
This is just a stand in until #127 is merged?

**Review by vbrancat — APPROVED** [review]
LGTM :)

**Comment by LiangJYu** [comment]
I think this PR can't be merged until the [isce3 on conda-forge](https://anaconda.org/conda-forge/isce3) gets bumpted to 0.12. It's still on 0.11.

**Comment by LiangJYu** [comment]
> I think this PR can't be merged until the [isce3 on conda-forge](https://anaconda.org/conda-forge/isce3) gets bumped to 0.12. It's still on 0.11. I think we'll need a new specifile for docker too.

Disregard above. Looks like it works with isce3 0.11.

**Pull request merged**
