### PR TITLE
Attempt to pin the reqs and add mambaforge for docs build

### PR DESCRIPTION
**Pull request by scottstanie**
Trying again to have the PR docs build now that I've turned on that setting.

### CODE REVIEW

**Comment by scottstanie** [comment]
Whew finally, https://opera-compass--170.org.readthedocs.build/en/170/

The main change that I did simply to make it as uniform with the Dolphin docs was to move the metadata from `setup.cfg` into `pyproject.toml`. I did this so we could do `pip install .[docs]`:
```
(mapping) staniewi:COMPASS$ pip install -e .[docs]
Obtaining file:///Users/staniewi/repos/COMPASS
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: pymdown-extensions in /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages (from compass==0.3.1) (9.9)
Requirement already satisfied: mkdocs in /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages (from compass==0.3.1) (1.4.2)
Requirement already satisfied: mkdocs-section-index in /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages (from compass==0.3.1) (0.3.4)
Requirement already satisfied: mkdocs-gen-files in /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages (from compass==0.3.1) (0.4.0)
Requirement already satisfied: mkdocs-material in /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages (from compass==0.3.1) (8.5.10)
Requirement already satisfied: mkdocstrings[python] in /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages (from compass==0.3.1) (0.19.0)
Requirement already satisfied: mkdocs-literate-nav in /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages (from compass==0.3.1) (0.5.0)
Requirement already satisfied: watchdog>=2.0 in /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages (from mkdocs->compass==0.3.1) (2.1.9)
Requirement already satisfied: markdown<3.4,>=3.2.1 in /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages (from mkdocs->compass==0.3.1) (3.3.7)
Requirement already satisfied: ghp-import>=1.0 in /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages (from mkdocs->compass==0.3.1) (2.1.0)
Requirement already satisfied: pyyaml-env-tag>=0.1 in /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages (from mkdocs->compass==0.3.1) (0.1)
Requirement already satisfied: click>=7.0 in /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages (from mkdocs->compass==0.3.1) (8.0.4)
Requirement already satisfied: jinja2>=2.11.1 in /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages (from mkdocs->compass==0.3.1) (3.1.2)
Requirement already satisfied: mergedeep>=1.3.4 in /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages (from mkdocs->compass==0.3.1) (1.3.4)
Requirement already satisfied: pyyaml>=5.1 in /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages (from mkdocs->compass==0.3.1) (5.4.1)
Requirement already satisfied: packaging>=20.5 in /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages (from mkdocs->compass==0.3.1) (23.0)
Requirement already satisfied: pygments>=2.12 in /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages (from mkdocs-material->compass==0.3.1) (2.14.0)
Requirement already satisfied: mkdocs-material-extensions>=1.1 in /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages (from mkdocs-material->compass==0.3.1) (1.1.1)
Requirement already satisfied: requests>=2.26 in /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages (from mkdocs-material->compass==0.3.1) (2.28.2)
Requirement already satisfied: MarkupSafe>=1.1 in /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages (from mkdocstrings[python]->compass==0.3.1) (2.1.1)
Requirement already satisfied: mkdocs-autorefs>=0.3.1 in /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages (from mkdocstrings[python]->compass==0.3.1) (0.4.1)
Requirement already satisfied: mkdocstrings-python>=0.5.2 in /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages (from mkdocstrings[python]->compass==0.3.1) (0.7.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages (from ghp-import>=1.0->mkdocs->compass==0.3.1) (2.8.2)
Requirement already satisfied: griffe>=0.11.1 in /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages (from mkdocstrings-python>=0.5.2->mkdocstrings[python]->compass==0.3.1) (0.21.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages (from requests>=2.26->mkdocs-material->compass==0.3.1) (2023.5.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages (from requests>=2.26->mkdocs-material->compass==0.3.1) (1.26.9)
Requirement already satisfied: idna<4,>=2.5 in /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages (from requests>=2.26->mkdocs-material->compass==0.3.1) (3.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages (from requests>=2.26->mkdocs-material->compass==0.3.1) (2.0.12)
Requirement already satisfied: six>=1.5 in /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages (from python-dateutil>=2.8.1->ghp-import>=1.0->mkdocs->compass==0.3.1) (1.16.0)
Building wheels for collected packages: compass
  Building editable for compass (pyproject.toml) ... done
  Created wheel for compass: filename=compass-0.3.1-0.editable-py3-none-any.whl size=7215 sha256=02d5afa67bc2787491cde9c1cddb809aa9ca6b60b9166acc4aad8cf7af36ec7c
  Stored in directory: /private/var/folders/hw/sj9hl8555s36n00t812twvcr0000gq/T/pip-ephem-wheel-cache-jzpq879x/wheels/e6/56/25/f3813609fca72c9fa490615207bc3d50c6f26da5cb087b2971
Successfully built compass
Installing collected packages: compass
  Attempting uninstall: compass
    Found existing installation: compass 0.3.1
    Uninstalling compass-0.3.1:
      Successfully uninstalled compass-0.3.1
Successfully installed compass-0.3.1
```

I'm sure there's a way to do it differently than how i solved the docs building/requirements problem, so if you feel strongly about keeping a setup.cfg, let me know.

**Review by vbrancat — APPROVED** [review]
LGTM :), thanks for working on that.

**Comment by vbrancat** [comment]
@LiangJYu can you review this PR? Merci

**Review by LiangJYu — APPROVED** [review]
LGTM

**Pull request merged**
