### PR TITLE
Docker for point release

### PR DESCRIPTION
**Pull request by seongsujeong**
This PR is the last planned PR before the upcoming point delivery. This PR updates specfile and the Dockerfile to generate the Docker image.

### CODE REVIEW

**Review by vbrancat — APPROVED** [review]
LGTM. Please, @LiangJYu take a look at this PR as well. Thanks.

**Comment by LiangJYu** [comment]
So we still need the isce3 build with the v.0.14.0 release?
https://github.com/isce-framework/isce3/releases/tag/v0.14.0

**Comment by seongsujeong** [comment]
No, I'll be using the ISCE3 from conda forge for the point release, but wanted to keep the another version of the Dockerfile (i.e. `Dockerfile.isce3_builder` and `specfile_isce3_builder`) somewhere in this code to expedite the test process regardless of the availability of the ISCE3 condo package.

**Review by LiangJYu — APPROVED** [review]
LGTM

**Pull request merged**
