### PR TITLE
Create CSLC for dual-pol case

### PR DESCRIPTION
**Pull request by vbrancat**
This PR allows to create CSLC products for the `dual-pol` polarization case i.e., when the original burst contains VV (or HH) and VH (or HV) polarizations. 

The radar burst to geocode and the output CSLC product contain the following bands for the following cases:
- **_co-pol no split-spectrum_:** 
         Band 1: VV (or HH) main band complex backscatter
- **_co-pol with split-spectrum_:** 
        Band 1: VV (or HH) low band complex backscatter
        Band 2: VV (or HH) main band complex backscatter
        Band 3: VV (or HH) high band complex backscatter
- **_dual-pol no split-spectrum_:**
        Band 1: VV (or HH) main band complex backscatter
        band 2: VH (or HV) main band complex backscatter
- **_dual-pol with split-spectrum_:**
        Band 1: VV (or HH) low band complex backscatter
        Band 2: VV (or HH) main band complex backscatter
        Band 3: VV (or HH) high band complex backscatter
        Band 4: VH (or HV) main band complex backscatter

Depending on the case the filename of the output CSLC is adjusted accordingly to reflect the number of polarization contained in the product

### CODE REVIEW

**Review by scottstanie — CHANGES_REQUESTED** [review]
This looks good, and both versions with and without range_split_spectrum worked in my dual-pol test!

The only other things that came up in my testing were not related to these immediate changes, so I'll submit something to fix those separately (specifically, the nodata values, and the band descriptions would be good to write instead of just `Band 1=Band 1`)

**Review by scottstanie — APPROVED** [review]

**Comment by vbrancat** [comment]
@LiangJYu and @seongsujeong does any of you has time to look at this PR? Thanks :)

**Review by LiangJYu — COMMENTED** [review]
I took a look but there are many merge conflicts so my comments are incomplete. I'll take another look after you merge.

**Comment by vbrancat** [comment]
> I took a look but there are many merge conflicts so my comments are incomplete. I'll take another look after you merge.

Fixed the conflicts but it's untested

**Review by LiangJYu — COMMENTED** [review]
`geo_metadata.py` needs to be deleted. It was previously deleted in the move to HDF5.

**Comment by vbrancat** [comment]
Too many conflicts. It will be easier to submit another PR. I am closing this and open a new one

**Pull request closed without merging**
