### PR TITLE
x/y coordinate and spacing datasets added to static layer output

### PR DESCRIPTION
**Pull request by LiangJYu**
This PR:
* adds missing x/y coordinates and spacing datasets to the topo static layers
* adds ability to generate topo static layers with `compass.s1_geocode_metadata`
* clean up unused yaml and debug `print`

### CODE REVIEW

**Comment by LiangJYu** [comment]
Now that topo static layers can be generated with `compass.s1_geocode_metadata`, should this ability be removed from `compass.s1_geocode_slc`?

**Comment by vbrancat** [comment]
No, this capability should not be removed from `s1_geocode_slc`. We promised PGE that the static layers would have been generated with the same SAS we use to generate the product. At some point, we want to add the capability to switch on/off the generation of the actual CSLC (to generate the static layers only)

**Review by vbrancat — COMMENTED** [review]
Thank you @LiangJYu for this PR. Two very broad comments:

1. Can we have the static layer product be named `static_layers_burst_id.h5` instead of `topo.h5`? In this way, we can guarantee that the filename is sort of unique
2. I do not want the static layers product to be too different from the actual CSLC-S1 product.
I am wondering whether we should allocate the static layers under `/science/SENTINEL1/CSLC/grids/static_layers`
3. In the static layer products we should have a burst_id metadata (may be following the same metadata tree of the CSLC-S1 product).

**Comment by LiangJYu** [comment]
> Thank you @LiangJYu for this PR. Two very broad comments:
> 
>     1. Can we have the static layer product be named `static_layers_burst_id.h5` instead of `topo.h5`? In this way, we can guarantee that the filename is sort of unique
> 
>     2. I do not want the static layers product to be too different from the actual CSLC-S1 product.
>        I am wondering whether we should allocate the static layers under `/science/SENTINEL1/CSLC/grids/static_layers`
> 
>     3. In the static layer products we should have a burst_id metadata (may be following the same metadata tree of the CSLC-S1 product).

All 3 points above have been addressed.

**Review by vbrancat — APPROVED** [review]
Thanks for having addressed my comments

**Review by seongsujeong — APPROVED** [review]
LGTM. Thanks for addressing my comments :)

**Pull request merged**
